name: Add labels

on:
  pull_request:
   types: [labeled]

jobs:
  addLabels:
    runs-on: ubuntu-latest
    if: contains(join(github.event.pull_request.labels.*.name, ' '), 'approved')
    steps:
      - name: labeled
        run: |
          echo "id:${{ github.event.comment.id }}"
          echo "label:${{ github.event.label.name }}"
          echo "labels:${{ github.event.pull_request.labels }}"
