on:
  issue_comment:
    types: [created]
    
jobs:
  commentCreated:
    runs-on: ubuntu-latest
    steps:
      - name: issue_comment
        run: |
          echo "id:${{ github.event.comment.id }}"
          echo "label:${{ github.event.label.name }}"
          echo "labels:${{ github.event.pull_request.labels }}"
