on:
  issue_comment:
    types: [created]
    
jobs:
  commentCreated:
    runs-on: ubuntu-latest
    steps:
      - name: issue_comment
        run: |
          echo ${{ github.event.comment.id }}
          echo ${{ github.event.pull_request.labels }}
