name: "Deploy on Comment"

on:
  pull_request_review_comment:
    
jobs:
  issue_commented:
    name: Issue comment
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "pull_request_review_comment"
